### ISSUE TITLE
[BUG] Connecting to Snowflake with `username_password_mfa` doesn't use caching

### ISSUE THREAD

**Issue by b-per** [dbt-labs/dbt-fusion#131]
**Describe the bug**

Connecting to Snowflake using `authenticator: username_password_mfa` triggers endless MFA requests, not caching the first successful MFA challenge.

This was tested in dbt Studio with Fusion (and extended attributes) as well as locally.

The impact might be quite wide with Snowflake enforcing MFA in the next few weeks/months.

**Is this a discrepancy between the dbt Fusion Engine and dbt Core? Check one.**
- [x] YES
- [ ] NO

Yes, in dbt-core, MFA is cached using the same `profiles.yml`

**To Reproduce**
- [enable token caching on Snowflake](https://docs.snowflake.com/en/user-guide/security-mfa#using-mfa-token-caching-to-minimize-the-number-of-prompts-during-authentication-optional)
- have a user with MFA in place
- set up a `profiles.yml` with user, password etc... and `authenticator: username_password_mfa`

Doing a `dbt run` in dbt Core caches MFA
Doing a `dbt run` in Fusion doesn't cache MFA

**Expected behavior**
MFA token is cached and people have to use Duo only once

**Comment by VersusFacit** [comment]
Addressed by https://github.com/dbt-labs/gosnowflake/pull/5 and https://github.com/dbt-labs/arrow-adbc/pull/25

**Comment by rscheuermann** [comment]
FYI, looks like this was included [August 18 in dbt-fusion 2.0.0-preview.1](https://github.com/dbt-labs/dbt-fusion/blob/main/CHANGELOG.md#dbt-fusion-200-preview1---august-18-2025)

That said, I'm still experiencing this issue with dbt LSP version 2.0.0-preview.92
